//! This code was AUTOGENERATED using the kinobi library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun kinobi to update it.
//!
//! [https://github.com/metaplex-foundation/kinobi]
//!

use bytemuck::{Pod, Zeroable};
use pinocchio::pubkey::Pubkey;

#[derive(Copy, Clone, Debug, Eq, PartialEq, Pod, Zeroable)]
#[repr(C)]
pub struct Creator {
    pub address: Pubkey,
    pub verified: u8, // 0 for false, 1 for true
    pub share: u8,
    pub present: u8,
    pub _padding: [u8; 7],
}

impl Creator {
    pub const NONE: u8 = 0;
    pub const SOME: u8 = 1;

    pub fn none() -> Self {
        Self {
            address: Pubkey::default(),
            verified: 0,
            share: 0,
            present: Self::NONE,
            _padding: [0; 7],
        }
    }

    pub fn some(address: Pubkey, verified: u8, share: u8) -> Self {
        Self {
            address,
            verified,
            share,
            present: Self::SOME,
            _padding: [0; 7],
        }
    }

    pub fn is_some(&self) -> bool {
        self.present == Self::SOME
    }

    pub fn is_none(&self) -> bool {
        self.present == Self::NONE
    }
}