//! This code was AUTOGENERATED using the kinobi library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun kinobi to update it.
//!
//! [https://github.com/metaplex-foundation/kinobi]
//!

use crate::api::metadata::collection::Collection;
use crate::api::metadata::creator::Creator;
use crate::api::metadata::uses::Uses;
use bytemuck::{Pod, Zeroable};

#[derive(Copy, Clone, Debug, Eq, PartialEq, Pod, Zeroable)]
#[repr(C)]
pub struct DataV2 {    
    pub uri: [u64; 32],
    pub seller_fee_basis_points: u16,
    pub name: [u8; 32],
    pub symbol: [u8; 10],
    pub creator_count: u8,
    pub creators: [Creator; 5],
    pub collection: Collection,
    pub uses: Uses,
}

impl Default for DataV2 {
    fn default() -> Self {
        Self {
            uri: [0; 32],
            seller_fee_basis_points: 0,
            name: [0; 32],
            symbol: [0; 10],
            creator_count: 0,
            creators: [Creator::none(); 5],
            collection: Collection::none(),
            uses: Uses::none(),
        }
    }
}